### ISSUE TITLE
How to consume GeoObject setGeoPosition long and lat from web service?

### ISSUE THREAD

**Issue by radityagumay** [BeyondAR/beyondar#50]
I just create web service http://radityalabs.net/wisata/lokasi.php, and i wanted to consume the services and places it into setGeoPosition and others element. How i can figure it?

Best regard

**Comment by estherooi** [comment]
@radityagumay Hi Radi, I am new to android studio. I have a same problem with you. How can I get the value from database and put into `SetGeoPosition` in the class CustomWorldHelper
Could you share with me how did you solve it? Thank you
