### ISSUE TITLE
Does not show Altitude in the GeoObject

### ISSUE THREAD

**Issue by Edwarded** [BeyondAR/beyondar#54]
Hello,

When i set an altitude in a Geoobject (for example, go1.setGeoPosition(40.331758 ,-3.767044, 10);

This object dissapear on the screen. If I set any kind of altitude value, the object stop being in the World.
1. I guess the value is in meters, right?
2. Do i need to set a user's altitude to be able to see the altitude objects?

I only want that; To see objects in different heights, but I can not.

Thank you in advance.

**Comment by abbydupre25** [comment]
I'm also having trouble with altitude. If it's not measured in meters, what is altitude really? Is it possible to render objects thousands of kilometers up? I've tried using setMaxDistanceToRender() and setPullCloserDistance(), but the objects still disappear after setting the altitude to even small values.

**Comment by pabloim2** [comment]
Same doubt as DavidDupre, can i set the real altitude to a geoObject?

**Comment by mrkxinthe** [comment]
The issue is closed - but looks like we can use this function to convert altitude in meters to GeoPoint values
com.beyondar.android.util.math.Distance.fastConversionMetersToGeoPoints
