### ISSUE TITLE
Image recognition

### ISSUE THREAD

**Issue by smanolakis23** [BeyondAR/beyondar#68]
Hi, 

I'm using beyondAR to create a world and display some GeoObjects, and everything works just fine. 
I'd like to know if it has the capability of image recognition, i.e. if I point a camera to a building, for which I have stored a picture of in my App, it can recognize it and display another picture on top of it. Not sure if it's clear what I'm trying to achieve. 

Any help would be very appreciated. 
Thank you

**Comment by joanpuigsanz** [comment]
Unfortunately there is no image recognition in the SDK, you could use vuforia sdk for this
