### ISSUE TITLE
The geobject becomes not showing when changed latitude and longitude after import into android studio

### ISSUE THREAD

**Issue by danial18** [BeyondAR/beyondar#70]
hi joanpuigsanz...i try import BeyondAR_Examples into android studio and succeed, can run in my android but after i change latitude and longitude with my location, geoobject not showing. please help me

**Comment by joanpuigsanz** [comment]
That's because the geoObjects have a different coordinate and they are too far to be displayed, put them closer and you will see them

See https://github.com/BeyondAR/beyondar/blob/master/android/BeyondAR_Examples/src/com/beyondar/example/CustomWorldHelper.java

**Comment by danial18** [comment]
I've tried to change their coordinates to the coordinates of the place around me but geobject not showing.

sharedWorld.setGeoPosition(-7.94290299541, 112.604235931);

GeoObject go2 = new GeoObject(2l);
        go2.setGeoPosition(-7.94279824355, 112.604269171);
        go2.setImageUri("http://beyondar.github.io/beyondar/images/logo_512.png");
        go2.setName("Online image");

**Comment by joanpuigsanz** [comment]
Then they are too far away,  try to put them closer

**Comment by kum-rah** [comment]
hey danial18, i tried importing the Beyondar_Example project but am getting this error message
- C:\Users\nmsl\AndroidStudioProjects\BeyondAR_Examples:
  java.io.IOException: The filename, directory name, or volume label syntax is incorrect

did you face any such thing? if so how did you fix it?
