### ISSUE TITLE
Showing Text on BeyondAr Object

### ISSUE THREAD

**Issue by hrskrs** [BeyondAR/beyondar#71]
`Is it possible to show content (Text), instad of an image?`
I am Woring on a google glass project. BeyondAr objects are loaded successfully, however i want to show as default(not when i click/touch beyondAr Onject) some content (ex: name or title of the object) instead of an image. How can i achieve that?

**Comment by joanpuigsanz** [comment]
You could attach a view or convert a view to an image.
See https://github.com/BeyondAR/beyondar/blob/master/android/BeyondAR_Examples/src/com/beyondar/example/AttachViewToGeoObjectActivity.java

https://github.com/BeyondAR/beyondar/blob/master/android/BeyondAR_Examples/src/com/beyondar/example/StaticViewGeoObjectActivity.java
