### ISSUE TITLE
Update GeoObjects depending on my location

### ISSUE THREAD

**Issue by joaoppedrosa** [BeyondAR/beyondar#80]
I want to show GeoObjects depending on my location, but i want to update the Geoobjects showing in BeyondarFragment as there my location is changing. Is any way to update the World in real time in the BeyondarFragment?

**Comment by IlCallo** [comment]
You must retrieve updated GPS coordinates of you position and then update the location of your World reference inside the BeyondarFragmentSupport

`mBeyondarFragment.getWorld().setLocation(location);`
